models/document.py
from . import MongoModel
from . import bool_dict
from models.mail import send_document
from flask import current_app as app


class Document(MongoModel):
    @classmethod
    def _fields(cls):
        fields = [
            ('user_uuid', str, ''),
            ('doc_url', str, ''),
            ('title', str, ''),
            ('public', bool, False),
            ('detail', str, ''),
            ('css', str, ''),
        ]
        fields.extend(super()._fields())
        return fields

    @classmethod
    def new(cls, form):
        m = super().new(form)
        from uuid import uuid4
        m.set_uuid(field='doc_url', seed=uuid4)
        m.save()
        return m

    def update_pic(self, pic):
        allowed_type = ['jpg', 'jpeg', 'gif', 'png']
        upload_name = pic.filename
        if upload_name != '' and upload_name.split('.')[-1] in allowed_type:
            path = app.config['USER_PIC_DIR']
            ext = app.config['PRODUCT_PIC_EXT']
            fullname = '{}{}.{}'.format(path, str(self.id), ext)
            pic.save(fullname)
            self.pic = '/' + fullname
            self.save()
        return self

    def set_pic_url(self, url):
        if len(url) > 0:
            self.pic = url
            self.save()

    def update_setting(self, form):
        form = form.to_dict()
        public = form.pop('public', 'false')
        form['public'] = bool_dict.get(public, False)
        if self.has(doc_url=form.get('doc_url')):
            form.pop('doc_url')
        self.update(form)
        return self

    def send_email(self, email):
        import markdown2
        detail_html = markdown2.markdown(self.detail)
        html = '<div id="preview">{}</div><style>{}</style>'.format(detail_html, self.css)
        send_document(email, self.title, html)

routes/admin.py
from routes import *
from models.document import Document
from models.user import User
from models.auth import Auth
from models.access import Access
from flask import current_app as app

import qiniu
from config import key

q = qiniu.Auth(key.qiniu_access_key, key.qiniu_secret_key)

main = Blueprint('admin', __name__)


@main.route('/document/<user_uuid>')
@admin_required
def document(user_uuid):
    cu = current_user()
    u = User.find_one(uuid=user_uuid)
    u.pics_url = [app.config['BASE_URL'] + app.config['USER_PIC_DIR'] + pic for pic in u.pics]
    u.pics_url.reverse()
    d = Document.find_one(user_uuid=u.uuid)
    d.doc_url_full_path = app.config['DOC_URL'] + d.doc_url
    return render_template('user/document.html', p=d, u=cu)


@main.route('/document/new', methods=['POST'])
@admin_required
def document_new():
    u = current_user()
    form = request.form
    status, msgs = Document.valid(form)
    if status is True:
        p = Document.new(form)
        return redirect(url_for('admin.document', uuid=p.uuid))
    else:
        return render_template('admin/document_new.html', msgs=msgs, u=u)


@main.route('/documents')
@admin_required
def documents():
    u = current_user()
    ms = Document.all()
    ms.reverse()
    for m in ms:
        m.user = User.find_one(uuid=m.user_uuid)
    return render_template('admin/documents.html', ms=ms, u=u)


@main.route('/document/<uuid>', methods=['POST'])
@admin_required
def document_update(uuid):
    p = Document.find_one(uuid=uuid)
    form = request.form
    p.update(form)
    return redirect(url_for('admin.document', uuid=p.uuid))


@main.route('/auths')
@admin_required
def auths():
    u = current_user()
    ms = Auth.all()
    ms.reverse()
    for m in ms:
        m.user = User.find_one(uuid=m.user_uuid)
        m.verified = m.verify()
    return render_template('admin/auths.html', ms=ms, u=u)


# ------------------------- 用户管理 --------------------------
@main.route('/users')
@admin_required
def users():
    u = current_user()
    ms = User.all()
    return render_template('admin/users.html', ms=ms, u=u)


@main.route('/users', methods=['POST'])
@admin_required
def users_search():
    u = current_user()
    form = request.form
    ms = User.search_or(form)
    return render_template('admin/users.html', u=u, ms=ms)


@main.route('/user/<int:id>')
@admin_required
def user(id):
    u = current_user()
    m = User.get(id)
    return render_template('admin/user.html', m=m, u=u)


@main.route('/user/delete/<int:id>')
@admin_required
def user_delete(id):
    # m = User.get(id)
    # m.delete()
    # TODO 先不让删
    return redirect(url_for('admin.users'))


@main.route('/user/update/<int:id>', methods=['POST'])
@admin_required
def user_update(id):
    m = User.get(id)
    form = request.form
    m.update_user(form)
    return redirect(url_for('admin.user', id=m.id))

# @main.route('/root')
# @login_required
# def root_set():
#     root = User.find_one(username='root')
#     root.role = 'admin'
#     root.save()
#     return redirect(url_for('admin.document_new'))


# @main.route('/root/reset')
# @login_required
# def root_reset():
#     root = User.find_one(username='root')
#     root.password = root.salted_password('123456')
#     root.save()
#     return redirect(url_for('admin.document_new'))

routes/document.py
from . import *
from models.document import Document
from models.auth import Auth

main = Blueprint('document', __name__)


@main.route('/<doc_url>')
def index(doc_url):
    u = current_user()
    d = Document.find_one(doc_url=doc_url)
    if d.public is True or (u is not None and d.user_uuid == u.uuid):
        return render_template('document.html', d=d, u=u)
    else:
        abort(401)


@main.route('/<doc_url>/token/<token>')
def protected(doc_url, token):
    u = current_user()
    d = Document.find_one(doc_url=doc_url)
    a = Auth.find_one(token=token, doc_uuid=d.uuid)
    if a is None:
        abort(401)
    if a.verify():
        a.used(request, success=True)
        text = '面试者对您的访问授权剩余{}次，授权过期时间：{}'.format(a.token_times, time_str(a.token_exp))
        flash(text, 'success')
        return render_template('document.html', d=d, u=u, token=token)
    else:
        a.used(request, success=False)
        abort(401)


@main.route('/<doc_url>/mail', methods=['POST'])
def send_mail(doc_url):
    u = current_user()
    form = request.form
    captcha = form.get('captcha', '').lower()
    email = form.get('email')
    token = form.get('token', '')
    if captcha != session.pop('captcha', 'no captcha!'):
        return json.dumps({'status': 'warning', 'msg': '验证码错误!'})
    d = Document.find_one(doc_url=doc_url)
    a = Auth.find_one(token=token, doc_uuid=d.uuid)
    public_valid = d.public is True
    owner_valid = u is not None and d.user_uuid == u.uuid
    token_valid = a is not None and a.verify()
    if public_valid or owner_valid:
        d.send_email(email)
        return json.dumps({'status': 'success', 'msg': '邮件已发送，未收到请检查垃圾箱。'})

    elif token_valid:
        d.send_email(email)
        a.used(request, success=True, mode='Send Email', email=email)
        return json.dumps({'status': 'success', 'msg': '邮件已发送，未收到请检查垃圾箱。本次请求已消耗您的授权1次。'})
    else:
        return json.dumps({'status': 'warning', 'msg': '您的请求未获得授权。'})


# @main.route('/mail')
# def send_mail_test():
#     from models.mail import send_by_sendcloud
#     send_by_sendcloud()
#
#     return json.dumps({'status': 'warning', 'msg': '您的请求未获得授权。'})

routes/ocr.py
from . import *
import base64
import requests


main = Blueprint('ocr', __name__)


@main.route('/')
def index():
    return render_template('ocr.html')


@main.route('/', methods=['POST'])
def parse():
    img = request.files.get('image')
    img = base64.b64encode(img.read())
    params = {"image": img}
    headers = {'Content-Type': 'application/x-www-form-urlencoded'}
    import config.key as key
    access_token = key.at
    url = 'https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic?access_token=' + access_token
    r = requests.post(url, data=params, headers=headers)
    try:
        d = json.loads(r.content.decode())
        words_list = d.get('words_result')
        # pprint.pprint(d)
        ps = [i.get('words') for i in words_list]
        p = ''.join(ps)
    except Exception as e:
        print(e)
        p = '解析失败，请重试。'
        ps = [p]
    return render_template('ocr.html', p=p, ps=ps)

routes/user.py
from routes import *
from models.user import User
from models.document import Document
from models.auth import Auth
from models.access import Access
from decimal import Decimal
from flask import current_app as app

main = Blueprint('user', __name__)

Model = User


@main.route('/login')
def index():
    if current_user() is not None:
        return redirect(url_for('user.dashboard'))
    return render_template('user/login.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    username = form.get('username', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.index'))
    u = User.find_one(username=username)
    if u is not None and u.validate_login(form):
        session['uid'] = u.id
        return redirect(url_for('user.dashboard'))
    else:
        flash('用户名密码错误', 'warning')
        return redirect(url_for('user.index'))


@main.route('/register')
def register_page():
    if current_user() is not None:
        return redirect(url_for('user.dashboard'))
    return render_template('user/register.html')


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.register'))
    status, msgs = User.valid(form)
    if status is True:
        u = User.new(form)
        u.send_email_verify(u.email)
        session['uid'] = u.id
        flash('验证邮件已发送，请查收', 'info')
        return redirect(url_for('user.dashboard'))
    else:
        for msg in msgs:
            flash(msg, 'warning')
        return redirect(url_for('user.register'))


@main.route('/password/forget')
def forget_password():
    if current_user() is not None:
        return redirect(url_for('user.dashboard'))
    return render_template('user/forget_password.html')


@main.route('/password/forget', methods=['POST'])
def forget_password_send():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.forget_password'))
    r = User.forget_password(form)
    if r:
        flash('密码重置邮件已经发送，请查收邮箱', 'success')
    else:
        flash('用户名或邮箱不匹配', 'warning')
    return redirect(url_for('user.forget_password'))


@main.route('/email/verify/<tb64>')
def email_verify(tb64):
    if User.email_verify(tb64):
        flash('邮箱验证通过', 'success')
    else:
        flash('邮箱验证失败', 'danger')
    return redirect(url_for('user.profile'))


@main.route('/password/forget/verify/<tb64>')
def forget_password_verify(tb64):
    if User.forget_password_verify(tb64):
        flash('重置邮件验证通过', 'success')
        return render_template('user/reset_password.html', tb64=tb64)
    else:
        flash('重置邮件验证失败', 'danger')
        return redirect(url_for('user.index'))


@main.route('/password/reset/<tb64>', methods=['POST'])
def reset_password(tb64):
    password = request.form.get('password', '')
    if User.forget_password_verify(tb64):
        u = User.get_user_by_tb64(tb64)
        u.reset_password(password)
        session['uid'] = u.id
        flash('密码已重置', 'success')
        return redirect(url_for('user.profile'))
    else:
        flash('重置邮件验证失败', 'warning')
        return redirect(url_for('user.index'))


@main.route('/avatar/upload', methods=['POST'])
@login_required
def avatar():
    u = current_user()
    avatar = request.files['avatar']
    u.update_avatar(avatar)
    return redirect(url_for('.profile'))


@main.route('/logout')
@login_required
def logout():
    p = session.pop('uid')
    print('logout: pop uid', p)
    flash('账号已安全退出', 'success')
    return redirect(url_for('user.login'))


@main.route('/dashboard')
@login_required
def dashboard():
    u = current_user()
    return render_template('user/dashboard.html', u=u)


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    d = Document.find_one(user_uuid=u.uuid)
    d.doc_url_full_path = app.config['DOC_URL'] + d.doc_url
    return render_template('user/profile.html', u=u, d=d)


@main.route('/profile', methods=['POST'])
@login_required
def profile_update():
    cu = current_user()
    form = request.form
    cu.safe_update_user(form)
    flash('信息已更新', 'success')
    return redirect(url_for('user.profile'))


@main.route('/email/update', methods=['POST'])
@login_required
def update_email():
    u = current_user()
    form = request.form
    new_email = form.get('email', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        return json.dumps({'status': 'warning', 'msg': '验证码错误'})
    if User.has(email=new_email) and User.find_one(email=new_email).uuid != u.uuid:
        return json.dumps({'status': 'warning', 'msg': '该邮箱已被占用'})
    if u.validate_login(form):
        u.send_email_verify(new_email)
        return json.dumps({'status': 'info', 'msg': '已发送验证邮件，请查收'})
    else:
        return json.dumps({'status': 'warning', 'msg': '密码错误'})


@main.route('/pic/upload', methods=['POST'])
@login_required
def pic_upload():
    u = current_user()
    pic = request.files['pic']
    pic = u.pic_upload(pic)
    if pic is not False:
        return json.dumps({'status': 'success', 'msg': '上传成功：' + pic, 'pic': pic})
    else:
        return json.dumps({'status': 'danger', 'msg': '上传失败'})


@main.route('/pic/del', methods=['POST'])
@login_required
def pic_del():
    u = current_user()
    pic = request.json.get('pic')
    u.pic_del(pic)
    return json.dumps({'status': 'success', 'msg': '已删除：' + pic})


@main.route('/document')
@login_required
def document():
    u = current_user()
    u.pics_url = [app.config['BASE_URL'] + app.config['USER_PIC_DIR'] + pic for pic in u.pics]
    u.pics_url.reverse()
    d = Document.find_one(user_uuid=u.uuid)
    d.doc_url_full_path = app.config['DOC_URL'] + d.doc_url
    return render_template('user/document.html', p=d, u=u)


@main.route('/document', methods=['POST'])
@login_required
def document_update():
    u = current_user()
    p = Document.find_one(user_uuid=u.uuid)
    form = request.form
    p.update(form)
    return redirect(url_for('user.document'))


@main.route('/document/setting', methods=['POST'])
@login_required
def document_setting():
    u = current_user()
    p = Document.find_one(user_uuid=u.uuid)
    form = request.form
    p.update_setting(form)
    flash('简历设置已更新', 'success')
    return redirect(url_for('user.profile'))


@main.route('/auths')
@login_required
@email_verify_required
def auths():
    u = current_user()
    auths = Auth.find(user_uuid=u.uuid)
    auths.reverse()
    for a in auths:
        a.verified = a.verify()
    return render_template('user/auths.html', u=u, auths=auths)


@main.route('/auths', methods=['POST'])
@login_required
def auths_search():
    u = current_user()
    form = request.form
    auths = Auth.search_or(form)
    auths.reverse()
    for a in auths:
        a.verified = a.verify()
    return render_template('user/auths.html', u=u, auths=auths)


@main.route('/auth/new')
@login_required
@email_verify_required
def auth_new():
    u = current_user()
    d = Document.find_one(user_uuid=u.uuid)
    form = dict(
        user_uuid=u.uuid,
        doc_uuid=d.uuid,
    )
    a = Auth.new(form)
    return redirect(url_for('user.auth', token=a.token))


@main.route('/auth/<token>')
@login_required
@email_verify_required
def auth(token):
    u = current_user()
    d = Document.find_one(user_uuid=u.uuid)
    d.base_url = app.config['BASE_URL'][:-1]
    a = Auth.find_one(token=token)
    a.verified = a.verify()
    history = Access.find(token=token, user_uuid=u.uuid)
    history.reverse()
    return render_template('user/auth.html', u=u, d=d, a=a, history=history)


@main.route('/auth/<token>', methods=['POST'])
@login_required
def auth_update(token):
    u = current_user()
    a = Auth.find_one(token=token)
    form = request.form
    if a.user_uuid == u.uuid:
        a.update_setting(form)
    return redirect(url_for('user.auth', token=token))

templates/base.html
<!doctype html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>
        {% block title %}
        简历生成器 - Power by Suzumiya
        {% endblock %}
    </title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery.form/4.2.1/jquery.form.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body data-channel="public">
<div class="container alert-container">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">×</span></button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
</div>
<script>
    $(document).ready(function () {
            $('.alert').delay(3000).fadeOut(600);
        }
    );
</script>
{% block head %}
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#base-nav-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="base-nav-collapse-1">
            {% block head_send_email %}
            {% endblock %}
            {% block head_login %}
                <ul class="nav navbar-nav navbar-right">
                    {% if u %}
                        {% if u.role=='admin' %}
                            <li class="dropdown">
                                <a class="dropdown-toggle"
                                   data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    管理员<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a class="" href="{{ url_for('admin.documents') }}">文档管理</a></li>
                                    <li><a class="" href="{{ url_for('admin.users') }}">用户管理</a></li>
                                    <li><a class="" href="{{ url_for('admin.auths') }}">授权管理</a></li>
                                </ul>
                            </li>
                        {% endif %}
                        <li class="dropdown">
                            <a class="dropdown-toggle"
                               data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                欢迎，{{ u.username }} <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a class="" href="{{ url_for('user.profile') }}">个人设置</a></li>
                                <li><a class="" href="{{ url_for('user.document') }}">我的简历</a></li>
                                <li><a class="" href="{{ url_for('user.auths') }}">授权管理</a></li>
                            </ul>
                        </li>
                        <li>
                            <a class="block-center" href="{{ url_for('user.logout') }}">
                                <span class="glyphicon glyphicon-off"></span> 登出
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <a class="block-center" href="{{ url_for('user.login') }}">
                                <span class="glyphicon glyphicon-log-in"></span> 登录
                            </a>
                        </li>
                        <li>
                            <a class="block-center" href="{{ url_for('user.register') }}">
                                <span class="glyphicon glyphicon-user"></span> 注册
                            </a>
                        </li>
                    {% endif %}
                </ul>
                {% endblock %}
            </div>
        </div>
    </nav>
{% endblock %}

<div class="main container page-wrap">
    {% block body %}
    {% endblock %}
</div>

{% block foot %}
    <footer class="bs-docs-footer">
        <div class="container">
            <ul class="footer-links">
                <li><a href="#">GitHub 仓库</a></li>
                <li><a href="#">协议</a></li>
                <li><a href="#">加入我们</a></li>
                <li><a href="#">关于</a></li>
            </ul>
            <p>
                Designed and built with all the love in the world by @Suzumiya.
            </p>
            <p>
                本项目源码受 MIT 开源协议保护.
            </p>
        </div>

    </footer>
{% endblock %}
</body>

</html>

templates/document.html
{% extends 'base.html' %}

{% block title %}
    {{ d.title }}
{% endblock %}

{% block head_send_email %}
    <form class="navbar-form navbar-left" action="{{ url_for('document.send_mail', doc_url=d.doc_url) }}" method="post"
          onsubmit="return ajaxSendMail();">
        <div class="form-group">
            <input type="email" class="form-control" id="id-input-send-email" name="email"
                   placeholder="输入邮箱地址以获取副本" required>
            <input name="captcha" class="form-control" placeholder="验证码" autocomplete="off" required>
            <input name="token" value='{{ token }}' hidden>
            <img onclick="this.setAttribute('src','/img/captcha/s?nocache='+Math.random());"
                 src="/img/captcha/s" alt="Captcha" class="right"/>
        </div>
        <button type="submit" class="btn btn-default">发送简历到邮箱</button>
    </form>
{% endblock %}

{% block head_login %}
    <ul class="nav navbar-nav navbar-right">
        {% if u and u.uuid == d.user_uuid %}
            <li>
                <a class="block-center" href="{{ url_for('user.document') }}">
                    <span class="glyphicon glyphicon-pencil"></span> 返回编辑
                </a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

{% block body %}

    <div hidden>
        <textarea id="text-input">{{ d.detail }}</textarea>
    </div>

    <div id="preview"></div>

    <style>{{ d.css }}</style>

    <script src="https://cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
    <script>
        function Editor(input, preview) {
            this.update = function () {
                preview.innerHTML = markdown.toHTML(input.value);
            };
            input.editor = this;
            this.update();
        }
        const log = function log() {
            console.log.apply(console, arguments);
        }

        new Editor(document.getElementById("text-input"), document.getElementById("preview"));

        let template = function (r) {
            let div = `
<div class="alert alert-${r.status} alert-dismissible" role="alert" >
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    ${r.msg}
</div>`
            return div
        }

        function ajaxSendMail() {
            let ajaxForm = $(event.target)
            let img = ajaxForm.find('img')
            img.click()
            ajaxForm.ajaxSubmit({
                success: function (message) {
                    r = JSON.parse(message)

                    $('.alert-container').append(template(r))
                    $('.alert').delay(2000).fadeOut(600)
                },

                clearForm: true,
            });
            return false;
        }
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div hidden>
    <textarea id="text-input">{{ d.detail }}</textarea>
</div>

<div id="preview"> </div>

<script src="https://cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
<script>
function Editor(input, preview) {
    this.update = function () {
        preview.innerHTML = markdown.toHTML(input.value);
    };
    input.editor = this;
    this.update();
}
const log = function log(){
  console.log.apply(console, arguments);
}

new Editor(document.getElementById("text-input"), document.getElementById("preview"));
</script>
{% endblock %}

templates/ocr.html
{% extends 'base.html' %}

{% block title %}
    图片文字识别
{% endblock %}

{% block head_login %}
    <ul class="nav navbar-nav navbar-left">
        <li>
            <a class="navbar-brand" href="#">图片文字识别</a>
        </li>
    </ul>
{% endblock %}

{% block body %}

    <div>
        <form class="form-inline" action="{{ url_for('ocr.parse') }}" method="post" enctype="multipart/form-data">
            <div class="input-group">
                <span class="input-group-addon">选择图片</span>
                <input type="file" class="form-control" name="image" id="image" required>
            </div>
            <button type="submit" class="btn btn-default">分析图片</button>
        </form>
    </div>
    <br>
    <div class="panel panel-info">
        <div class="panel-heading">
            图片大小不超过4M，最短边至少15px，最长边最大4096px，支持jpg/png/bmp格式
        </div>
    </div>

    <div class="jumbotron" style="min-height: 400px;">
        {% for foo in ps %}
            <p>{{ foo }}</p>
        {% endfor %}
    </div>
{% endblock %}