models/auth.py
from . import MongoModel
from . import timestamp
from models.access import Access
from datetime import datetime
import time
from flask import current_app as app


class Auth(MongoModel):
    @classmethod
    def _fields(cls):
        fields = [
            ('user_uuid', str, ''),
            ('doc_uuid', str, ''),
            ('comment', str, ''),
            ('token', str, ''),
            ('token_exp', int, 0),
            ('token_times', int, 0),
            ('visited_times', int, 0),
        ]
        fields.extend(super()._fields())
        return fields

    @classmethod
    def new(cls, form):
        m = super().new(form)
        m.set_uuid(field='token')
        m.save()
        return m

    def update_setting(self, form):
        form = form.to_dict()
        form.pop('token')
        token_exp = form.pop('token_exp')
        token_exp = datetime.strptime(token_exp, '%Y-%m-%dT%H:%M')
        token_times = form.pop('token_times')
        form['token_times'] = int(token_times)
        form['token_exp'] = int(token_exp.timestamp())
        self.update(form)
        return self

    def verify(self):
        now = timestamp()
        if self.token_times > 0 and self.token_exp > now:
            return True
        else:
            return False

    def used(self, request, success=True, mode='Web', email=''):
        form = dict(
            token=self.token,
            user_uuid=self.user_uuid,
            mode=mode,
            email=email,
            doc_uuid=self.doc_uuid,
            platform=request.user_agent.platform,
            browser=request.user_agent.browser,
            version=request.user_agent.version,
            user_agent=request.user_agent.string,
            ip=request.headers.get("X-real-ip"),
            x_forwarded_for=request.headers.getlist("X-Forwarded-For"),
            success=success,
        )
        Access.new(form)
        if success:
            self.token_times -= 1
            self.visited_times += 1
            self.save()

models/document.py
from . import MongoModel
from . import bool_dict
from models.mail import send_document
from flask import current_app as app


class Document(MongoModel):
    @classmethod
    def _fields(cls):
        fields = [
            ('user_uuid', str, ''),
            ('doc_url', str, ''),
            ('title', str, ''),
            ('public', bool, False),
            ('detail', str, ''),
            ('css', str, ''),
        ]
        fields.extend(super()._fields())
        return fields

    @classmethod
    def new(cls, form):
        m = super().new(form)
        from uuid import uuid4
        m.set_uuid(field='doc_url', seed=uuid4)
        m.save()
        return m

    def update_pic(self, pic):
        allowed_type = ['jpg', 'jpeg', 'gif', 'png']
        upload_name = pic.filename
        if upload_name != '' and upload_name.split('.')[-1] in allowed_type:
            path = app.config['USER_PIC_DIR']
            ext = app.config['PRODUCT_PIC_EXT']
            fullname = '{}{}.{}'.format(path, str(self.id), ext)
            pic.save(fullname)
            self.pic = '/' + fullname
            self.save()
        return self

    def set_pic_url(self, url):
        if len(url) > 0:
            self.pic = url
            self.save()

    def update_setting(self, form):
        form = form.to_dict()
        public = form.pop('public', 'false')
        form['public'] = bool_dict.get(public, False)
        if self.has(doc_url=form.get('doc_url')):
            form.pop('doc_url')
        self.update(form)
        return self

    def send_email(self, email):
        import markdown2
        detail_html = markdown2.markdown(self.detail)
        html = '<div id="preview">{}</div><style>{}</style>'.format(detail_html, self.css)
        send_document(email, self.title, html)

routes/document.py
from . import *
from models.document import Document
from models.auth import Auth

main = Blueprint('document', __name__)


@main.route('/<doc_url>')
def index(doc_url):
    u = current_user()
    d = Document.find_one(doc_url=doc_url)
    if d.public is True or (u is not None and d.user_uuid == u.uuid):
        return render_template('document.html', d=d, u=u)
    else:
        abort(401)


@main.route('/<doc_url>/token/<token>')
def protected(doc_url, token):
    u = current_user()
    d = Document.find_one(doc_url=doc_url)
    a = Auth.find_one(token=token, doc_uuid=d.uuid)
    if a is None:
        abort(401)
    if a.verify():
        a.used(request, success=True)
        text = '面试者对您的访问授权剩余{}次，授权过期时间：{}'.format(a.token_times, time_str(a.token_exp))
        flash(text, 'success')
        return render_template('document.html', d=d, u=u, token=token)
    else:
        a.used(request, success=False)
        abort(401)


@main.route('/<doc_url>/mail', methods=['POST'])
def send_mail(doc_url):
    u = current_user()
    form = request.form
    captcha = form.get('captcha', '').lower()
    email = form.get('email')
    token = form.get('token', '')
    if captcha != session.pop('captcha', 'no captcha!'):
        return json.dumps({'status': 'warning', 'msg': '验证码错误!'})
    d = Document.find_one(doc_url=doc_url)
    a = Auth.find_one(token=token, doc_uuid=d.uuid)
    public_valid = d.public is True
    owner_valid = u is not None and d.user_uuid == u.uuid
    token_valid = a is not None and a.verify()
    if public_valid or owner_valid:
        d.send_email(email)
        return json.dumps({'status': 'success', 'msg': '邮件已发送，未收到请检查垃圾箱。'})

    elif token_valid:
        d.send_email(email)
        a.used(request, success=True, mode='Send Email', email=email)
        return json.dumps({'status': 'success', 'msg': '邮件已发送，未收到请检查垃圾箱。本次请求已消耗您的授权1次。'})
    else:
        return json.dumps({'status': 'warning', 'msg': '您的请求未获得授权。'})


# @main.route('/mail')
# def send_mail_test():
#     from models.mail import send_by_sendcloud
#     send_by_sendcloud()
#
#     return json.dumps({'status': 'warning', 'msg': '您的请求未获得授权。'})

routes/user.py
from routes import *
from models.user import User
from models.document import Document
from models.auth import Auth
from models.access import Access
from decimal import Decimal
from flask import current_app as app

main = Blueprint('user', __name__)

Model = User


@main.route('/login')
def index():
    if current_user() is not None:
        return redirect(url_for('user.dashboard'))
    return render_template('user/login.html')


@main.route('/login', methods=['POST'])
def login():
    form = request.form
    username = form.get('username', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.index'))
    u = User.find_one(username=username)
    if u is not None and u.validate_login(form):
        session['uid'] = u.id
        return redirect(url_for('user.dashboard'))
    else:
        flash('用户名密码错误', 'warning')
        return redirect(url_for('user.index'))


@main.route('/register')
def register_page():
    if current_user() is not None:
        return redirect(url_for('user.dashboard'))
    return render_template('user/register.html')


@main.route('/register', methods=['POST'])
def register():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.register'))
    status, msgs = User.valid(form)
    if status is True:
        u = User.new(form)
        u.send_email_verify(u.email)
        session['uid'] = u.id
        flash('验证邮件已发送，请查收', 'info')
        return redirect(url_for('user.dashboard'))
    else:
        for msg in msgs:
            flash(msg, 'warning')
        return redirect(url_for('user.register'))


@main.route('/password/forget')
def forget_password():
    if current_user() is not None:
        return redirect(url_for('user.dashboard'))
    return render_template('user/forget_password.html')


@main.route('/password/forget', methods=['POST'])
def forget_password_send():
    form = request.form
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        flash('验证码错误', 'warning')
        return redirect(url_for('user.forget_password'))
    r = User.forget_password(form)
    if r:
        flash('密码重置邮件已经发送，请查收邮箱', 'success')
    else:
        flash('用户名或邮箱不匹配', 'warning')
    return redirect(url_for('user.forget_password'))


@main.route('/email/verify/<tb64>')
def email_verify(tb64):
    if User.email_verify(tb64):
        flash('邮箱验证通过', 'success')
    else:
        flash('邮箱验证失败', 'danger')
    return redirect(url_for('user.profile'))


@main.route('/password/forget/verify/<tb64>')
def forget_password_verify(tb64):
    if User.forget_password_verify(tb64):
        flash('重置邮件验证通过', 'success')
        return render_template('user/reset_password.html', tb64=tb64)
    else:
        flash('重置邮件验证失败', 'danger')
        return redirect(url_for('user.index'))


@main.route('/password/reset/<tb64>', methods=['POST'])
def reset_password(tb64):
    password = request.form.get('password', '')
    if User.forget_password_verify(tb64):
        u = User.get_user_by_tb64(tb64)
        u.reset_password(password)
        session['uid'] = u.id
        flash('密码已重置', 'success')
        return redirect(url_for('user.profile'))
    else:
        flash('重置邮件验证失败', 'warning')
        return redirect(url_for('user.index'))


@main.route('/avatar/upload', methods=['POST'])
@login_required
def avatar():
    u = current_user()
    avatar = request.files['avatar']
    u.update_avatar(avatar)
    return redirect(url_for('.profile'))


@main.route('/logout')
@login_required
def logout():
    p = session.pop('uid')
    print('logout: pop uid', p)
    flash('账号已安全退出', 'success')
    return redirect(url_for('user.login'))


@main.route('/dashboard')
@login_required
def dashboard():
    u = current_user()
    return render_template('user/dashboard.html', u=u)


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    d = Document.find_one(user_uuid=u.uuid)
    d.doc_url_full_path = app.config['DOC_URL'] + d.doc_url
    return render_template('user/profile.html', u=u, d=d)


@main.route('/profile', methods=['POST'])
@login_required
def profile_update():
    cu = current_user()
    form = request.form
    cu.safe_update_user(form)
    flash('信息已更新', 'success')
    return redirect(url_for('user.profile'))


@main.route('/email/update', methods=['POST'])
@login_required
def update_email():
    u = current_user()
    form = request.form
    new_email = form.get('email', '')
    captcha = form.get('captcha', '').lower()
    if captcha != session.pop('captcha', 'no captcha!'):
        return json.dumps({'status': 'warning', 'msg': '验证码错误'})
    if User.has(email=new_email) and User.find_one(email=new_email).uuid != u.uuid:
        return json.dumps({'status': 'warning', 'msg': '该邮箱已被占用'})
    if u.validate_login(form):
        u.send_email_verify(new_email)
        return json.dumps({'status': 'info', 'msg': '已发送验证邮件，请查收'})
    else:
        return json.dumps({'status': 'warning', 'msg': '密码错误'})


@main.route('/pic/upload', methods=['POST'])
@login_required
def pic_upload():
    u = current_user()
    pic = request.files['pic']
    pic = u.pic_upload(pic)
    if pic is not False:
        return json.dumps({'status': 'success', 'msg': '上传成功：' + pic, 'pic': pic})
    else:
        return json.dumps({'status': 'danger', 'msg': '上传失败'})


@main.route('/pic/del', methods=['POST'])
@login_required
def pic_del():
    u = current_user()
    pic = request.json.get('pic')
    u.pic_del(pic)
    return json.dumps({'status': 'success', 'msg': '已删除：' + pic})


@main.route('/document')
@login_required
def document():
    u = current_user()
    u.pics_url = [app.config['BASE_URL'] + app.config['USER_PIC_DIR'] + pic for pic in u.pics]
    u.pics_url.reverse()
    d = Document.find_one(user_uuid=u.uuid)
    d.doc_url_full_path = app.config['DOC_URL'] + d.doc_url
    return render_template('user/document.html', p=d, u=u)


@main.route('/document', methods=['POST'])
@login_required
def document_update():
    u = current_user()
    p = Document.find_one(user_uuid=u.uuid)
    form = request.form
    p.update(form)
    return redirect(url_for('user.document'))


@main.route('/document/setting', methods=['POST'])
@login_required
def document_setting():
    u = current_user()
    p = Document.find_one(user_uuid=u.uuid)
    form = request.form
    p.update_setting(form)
    flash('简历设置已更新', 'success')
    return redirect(url_for('user.profile'))


@main.route('/auths')
@login_required
@email_verify_required
def auths():
    u = current_user()
    auths = Auth.find(user_uuid=u.uuid)
    auths.reverse()
    for a in auths:
        a.verified = a.verify()
    return render_template('user/auths.html', u=u, auths=auths)


@main.route('/auths', methods=['POST'])
@login_required
def auths_search():
    u = current_user()
    form = request.form
    auths = Auth.search_or(form)
    auths.reverse()
    for a in auths:
        a.verified = a.verify()
    return render_template('user/auths.html', u=u, auths=auths)


@main.route('/auth/new')
@login_required
@email_verify_required
def auth_new():
    u = current_user()
    d = Document.find_one(user_uuid=u.uuid)
    form = dict(
        user_uuid=u.uuid,
        doc_uuid=d.uuid,
    )
    a = Auth.new(form)
    return redirect(url_for('user.auth', token=a.token))


@main.route('/auth/<token>')
@login_required
@email_verify_required
def auth(token):
    u = current_user()
    d = Document.find_one(user_uuid=u.uuid)
    d.base_url = app.config['BASE_URL'][:-1]
    a = Auth.find_one(token=token)
    a.verified = a.verify()
    history = Access.find(token=token, user_uuid=u.uuid)
    history.reverse()
    return render_template('user/auth.html', u=u, d=d, a=a, history=history)


@main.route('/auth/<token>', methods=['POST'])
@login_required
def auth_update(token):
    u = current_user()
    a = Auth.find_one(token=token)
    form = request.form
    if a.user_uuid == u.uuid:
        a.update_setting(form)
    return redirect(url_for('user.auth', token=token))

templates/user/auth.html
{% extends 'base.html' %} {% block body %}
<ol class="breadcrumb">
    <li><a href="{{ url_for('user.auths') }}">My Auths</a></li>
    <li class="active">Auth Token</li>
</ol>
<div class="row">
    <div class="col-xs-12 col-sm-6">
        <h3>授权码设置</h3>
        <div class="panel-profile">
            <form method=POST enctype=multipart/form-data action="{{ url_for('user.auth_update', token=a.token) }}">
                <label>URL</label>
                <div>
                    {{ d.base_url + url_for('document.protected',doc_url=d.doc_url, token=a.token) }}
                </div>
                <label>授权码
                        <input class="form-control" name="token" value="{{ a.token }}" readonly>
                    </label>
                <label>备注
                        <input class="form-control" name="comment" value="{{ a.comment }}">
                    </label>
                <label>剩余次数
                        <input class="form-control" name="token_times" value="{{ a.token_times }}" type="number">
                    </label>
                <label>有效期
                        <input class="form-control" name="token_exp" value="{{ a.token_exp|time_str_datetime }}"
                               type="datetime-local">
                    </label>
                <label>状态:
                        {% if a.verified %}
                            <span class="text-success">生效中</span>
                        {% else %}
                            <span class="text-danger">已失效</span>
                        {% endif %}
                    </label>
                <br>
                <button class="btn btn-success btn-block">提交</button>
            </form>
        </div>
    </div>

</div>

<hr>
<h3>访问历史</h3>
<div class="container-fluid">
    {% for i in history %}
    <div class="row panel {% if i.success %} panel-success {% else %} panel-danger {% endif %}">
        <div class="panel-heading">访问时间：{{ i.ct|time_str }} 授权通过：{{ i.success }}</div>
        <div class="panel-body ">
            <div> 访问方式：{{ i.mode }} {{ i.email }}</div>
            <div> 操作系统：{{ i.platform }} </div>
            <div> 浏览器：{{ i.browser }} {{ i.version }} </div>
            <div> 访问来源：{{ i.ip }} </div>
            <div> User Agent：{{ i.user_agent }} </div>
        </div>

    </div>
    {% endfor %}
</div>
{% endblock %}

templates/user/auths.html
{% extends 'base.html' %}
{% block body %}
    <div class="">
        <h1>My Auths</h1>

    </div>
    <form class="navbar-form " action="{{ url_for('user.auths_search') }}" method="post">
        <a href="{{ url_for('user.auth_new') }}" class="btn btn-info right">生成授权码</a>
        <input type="text" class="form-control" name="token" placeholder="按token检索">
        <input type="text" class="form-control" name="comment" placeholder="按备注检索">
        <button type="submit" class="btn btn-default">Search</button>
    </form>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th class="th-col-2">授权码</th>
            <th class="th-col-3">备注</th>
            <th class="th-col-1">访问次数</th>
            <th class="th-col-1">剩余次数</th>
            <th class="th-col-2">过期时间</th>
            <th class="th-col-1">状态</th>
        </tr>
        </thead>
        <tbody>
        {% for a in auths %}
            <tr data-id={{ a.token }}>
                <td>
                    <a href="{{ url_for('user.auth', token=a.token) }}">{{ a.token }}</a>
                </td>
                <td>{{ a.comment }}</td>
                <td>{{ a.visited_times }}</td>
                <td>{{ a.token_times }}</td>
                <td>{{ a.token_exp|time_str }}</td>
                <td>
                    {% if a.verified %}
                        <p class="text-success">生效中</p>
                    {% else %}
                        <p class="text-danger">已失效</p>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/dashboard.html
{% extends 'base.html' %}
{% block body %}

    <div class="page-header">
        <h1>My Dashboard
            <small>Welcome to Suzumiya Career Center!</small>
        </h1>
    </div>

    <div class="well well-padding-width">
        <h2>个人设置</h2>
        <h3><small>修改密码、验证邮箱、设置简历Title、URL、是否公开。</small></h3>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('user.profile') }}" role="button">点击进入</a></p>
    </div>

    <div class="well well-padding-width">
        <h2>我的简历</h2>
        <h3><small>使用Markdown语法编辑简历内容，支持自定义CSS，支持上传图片（每人上限20张，单个不超过2MB）。</small></h3>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('user.document') }}" role="button">点击进入</a></p>
    </div>

    <div class="well well-padding-width">
        <h2>授权管理</h2>
        <h3><small>对于私有简历，生成授权码以允许对方查看，并可设置授权次数及有效期限。
            <br>「生成多个授权码发给不同申请单位，即可据此追踪访问者的足迹！」</small></h3>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('user.auths') }}" role="button">点击进入</a></p>
    </div>

{% endblock %}

templates/user/document.html
{% extends 'base.html' %}
{% block body %}

    <div>
        {{ msgs }}
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <div class="">
                简历地址：
                <a href="{{ p.doc_url_full_path }}">
                    {{ p.doc_url_full_path }}
                </a>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading toggle-panel-heading">
                    上传图片
                    <span class="glyphicon glyphicon-chevron-down right"></span>
                </div>
                <div class="panel-body" hidden>
                    <form method="post" enctype="multipart/form-data" action="{{ url_for('user.pic_upload') }}"
                          onsubmit="return ajaxPicUpload();">
                        <input name="pic" type="file" class="form-control" id="id-input-file-pic-upload" required>
                        <button class="btn btn-success">上传图片</button>
                    </form>
                    <div class="img-upload-item-container">
                    {% for i in u.pics_url %}
                        <div class="img-upload-item" data-name="{{ i }}">
                            <img src="{{ i }}" alt="" class="img-user-pic-preview">
                            <div class="right img-url-text">
                                <div>{{ i }}</div>
                                <a href="#" class="btn btn-danger btn-xs right btn-img-del">删除</a>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
            <form method=POST enctype=multipart/form-data action="{{ url_for('user.document_update') }}">

                <div class="panel panel-default">
                    <div class="panel-heading toggle-panel-heading">
                        自定义CSS
                        <span class="glyphicon glyphicon-chevron-down right"></span>
                    </div>
                    <div class="panel-body" hidden>
                        <textarea class="form-control" rows="8" name="css">{{ p.css }}</textarea>
                    </div>
                </div>
                <label for="text-input">简历内容</label>
                <textarea id="text-input" oninput="this.editor.update()"
                          class="form-control" rows="20" name="detail">{{ p.detail }}</textarea>
                <hr>
                <button class="btn btn-success btn-block">保存</button>
            </form>
        </div>
        <div class="col-xs-12 col-sm-6">
            <div id="preview"></div>
            <style>{{ p.css }}</style>
        </div>
    </div>
    <script src="https://cdn.bootcss.com/markdown.js/0.5.0/markdown.min.js"></script>
    <script src="{{ url_for('static', filename='js/document.js') }}"></script>

{% endblock %}

templates/user/forget_password.html
{% extends 'base.html' %} {% block body %}
<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

<div id="id-div-login" class="div-form sign-flow">
    <form method="post" action="{{ url_for('user.forget_password') }}">
        <div class="group-inputs">
            <input name="username" id="id-input-username" placeholder="用户名" required>
            <input name="email" type="email" id="id-input-email" placeholder="邮箱" required>
            <input name="captcha" id="id-input-captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
            <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());" src="/img/captcha" alt="Captcha" class="right" />
        </div>
        <br>
        <button class="btn btn-danger btn-block">找回密码</button>
        <a class="right text-muted" href="{{ url_for('user.login') }}">我又想起来了</a>
    </form>
</div>

<div id="particles-js"></div>
<script type="text/javascript">
    particlesJS.load('particles-js', '/static/js/particles.json');
</script>

{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block body %}
    <script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

    <div id="id-div-login" class="div-form sign-flow">
        <form method="post" action="{{ url_for('user.login') }}">
            <div class="group-inputs">
                <input name="username" id="id-input-username" placeholder="用户名" required>
                <input name="password" id="id-input-password" type="password" placeholder="密码" required>
                <input name="captcha" id="id-input-captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
                <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());"
                     src="/img/captcha" alt="Captcha" class="right"/>
            </div>
            <br>
            <button class="btn btn-default btn-block">登录</button>
            <a class="right text-muted" href="{{ url_for('user.forget_password') }}">忘记密码</a>

        </form>
    </div>

    <div id="particles-js"></div>
    <script type="text/javascript">
        particlesJS.load('particles-js', '/static/js/particles.json');
    </script>

{% endblock %}

templates/user/profile.html
{% extends 'base.html' %} {% block body %}
    <div>
        <h1>Profile</h1>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <div class="panel panel-default panel-profile">
                <div class="panel-heading">用户名及密码</div>
                <div class="panel-body">
                    <form method=POST enctype=multipart/form-data action="{{ url_for('user.profile_update') }}">
                        <label for="id-name">用户名</label>
                        <input class="form-control" name="username" id=id-name value="{{ u.username }}" readonly>
                        <label for="id-password">修改密码</label>
                        <input class="form-control" name=password id=id-password>
                        <label for="id-re-password">重复密码</label>
                        <input class="form-control" name=re_password id=id-re-password>
                        <hr>
                        <button class="btn btn-success btn-block">提交修改密码</button>
                    </form>
                </div>
            </div>

            <div class="panel panel-default panel-profile">
                <div class="panel-heading">邮箱信息</div>
                <div class="panel-body">

                    <div id=id-div-email-info>
                        <label>
                            邮箱
                            <div class="">
                                {{ u.email }}
                            </div>
                        </label>

                        <label>
                            验证状态
                            {% if u.email_verify %}
                                <p class="text-success">
                                    通过
                                </p>
                            {% else %}
                                <p class="text-danger">
                                    未验证
                                </p>
                            {% endif %}
                        </label>
                        <br>
                        <button class="btn btn-info btn-block button-re-verify" id=id-button-re-verify>更新验证</button>
                    </div>

                    <div id="id-div-email-update" class="" hidden>
                        <form method="post" action="{{ url_for('user.update_email') }}"
                              onsubmit="return ajaxFormSubmit()">
                            <div class="group-inputs">
                                <input name="password" type=password placeholder="密码" required>
                                <input name="email" type="email" placeholder="新邮箱" required>
                                <input name="captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
                            </div>
                            <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());"
                                 src="/img/captcha"
                                 alt="Captcha" class=""/>
                            <br>
                            <button class="btn btn-info btn-block" id=id-button-verify type=submit>获取验证邮件</button>
                            <button class="btn btn-default btn-block button-re-verify" type=button>取消更新</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-6">
            <div class="panel panel-default panel-profile">
                <div class="panel-heading">简历信息</div>
                <div class="panel-body">
                    <form method=POST enctype=multipart/form-data action="{{ url_for('user.document_setting') }}">
                        <label for="id-doc-title">简历Title</label>
                        <input class="form-control" name=title id="id-doc-title" value="{{ d.title }}">
                        <label for="id-doc-url">设置URL</label>
                        <input class="form-control" name=doc_url id=id-doc-url value="{{ d.doc_url }}">
                        <label>预览URL</label>
                        <a href="#">
                            {{ d.doc_url_full_path }}
                        </a>
                        <label for="id-doc-public">授权访问</label>
                        <select name="public" class="form-control" id=id-doc-public>
                            <option value=true {% if d.public %} selected {% endif %}>公开</option>
                            <option value=false {% if not d.public %} selected {% endif %}>私有</option>
                        </select>
                        <hr>
                        <button class="btn btn-success btn-block">提交简历设置</button>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <script src="{{ url_for('static', filename='js/profile.js') }}"></script>

{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% block body %}
<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

<div id="id-div-register" class="div-form sign-flow">
    <form method="post" action="{{ url_for('user.register') }}">
        <div class="group-inputs">
            <input name="username" id="id-input-username" placeholder="用户名" required>
            <input name="password" id="id-input-password" placeholder="密码" required>
            <input name="email" type="email" id="id-input-email" placeholder="邮箱" required>
            <input name="captcha" id="id-input-captcha" placeholder="验证码（不区分大小写）" autocomplete="off" required>
            <img onclick="this.setAttribute('src','/img/captcha?nocache='+Math.random());"
                 src="/img/captcha" alt="Captcha" class="right"/>
            <!-- <input name="captcha" id="id-input-mail-code" placeholder="邮箱码" required>
            <button class="btn btn-info right" id=id-button-mail-code type=button>获取</button> -->
        </div>
        <br>
        <button class="btn btn-default btn-block">注册</button>
    </form>
</div>

<div id="particles-js"></div>
<script type="text/javascript">
    particlesJS.load('particles-js', '/static/js/particles.json');
</script>



{% endblock %}

templates/user/reset_password.html
{% extends 'base.html' %} {% block body %}
<script src="https://cdn.bootcss.com/particles.js/2.0.0/particles.min.js"></script>

<div id="id-div-login" class="div-form sign-flow">
    <form method="post" action="{{ url_for('user.reset_password', tb64=tb64) }}">
        <div class="group-inputs">
            <input name="password" id="id-input-password"  placeholder="新密码" required>
        </div>
        <br>
        <button class="btn btn-default btn-block">设置新密码</button>
    </form>
</div>

<div id="particles-js"></div>
<script type="text/javascript">
    particlesJS.load('particles-js', '/static/js/particles.json');
</script>

{% endblock %}